export { default as car1} from './car1.png'
export { default as car2} from './car2.png'
export { default as car3} from './car3.png'
export { default as black_audi } from './black_audi.png'
export { default as blue_suzuki } from './blue_suzuki.png'
export { default as gray_suzuki } from './gray_suzuki.png'
export { default as mercedes } from './mercedes.png'
export { default as toyota } from './toyota.png'
export { default as white_audi } from './white_audi.png'
